# The URL the site will be built for
base_url = "https://example.com"

generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# highlight_theme = "eden-mono"
highlight_theme = "quiet-light"
# highlight_themes_css = [
#   { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
#   { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
# ]
extra_syntaxes_and_themes = ["highlight-themes"]
[extra]
# Put all your custom variables here
